services:
  domserver:
    image: domjudge/domserver:8.2.3
    container_name: domserver
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_DATABASE: ${DJ_DB}
      MYSQL_USER: ${DJ_DB_USER}
      MYSQL_PASSWORD: ${DJ_DB_PASSWORD}
      MYSQL_ROOT_USER: ${DB_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      CONTAINER_TIMEZONE: Asia/Kolkata
      FPM_MAX_CHILDREN: 40
    volumes:
      - submissions-data:/opt/domjudge/domserver/submissions/
      - judgings-data:/opt/domjudge/domserver/judgings/
      - ./50-domjudge.sh:/scripts/start.d/50-domjudge.sh
    # networks:
      # - mariadb-network
      # - judge-network
      # - traefik-public
    # labels:
    #   - traefik.enable=true
    #   - traefik.docker.network=traefik-public
    #   - traefik.constraint-label=traefik-public
    #   - traefik.http.middlewares.prod-redirect.redirectscheme.scheme=https
    #   - traefik.http.routers.domserver-http.rule=Host(${SITES})
    #   - traefik.http.routers.domserver-http.entrypoints=http
    #   - traefik.http.routers.domserver-http.middlewares=prod-redirect
    #   - traefik.http.routers.domserver-https.rule=Host(${SITES})
    #   - traefik.http.routers.domserver-https.entrypoints=https
    #   - traefik.http.routers.domserver-https.tls=true
    #   - traefik.http.routers.domserver-https.tls.certresolver=le
    #   - traefik.http.services.domserver.loadbalancer.server.port=80

volumes:
  submissions-data:
    name: domserver-submissions-data
  judgings-data:
    name: domserver-judgings-data

# networks:
#   mariadb-network:
#     name: mariadb-network
#     external: true
#   judge-network:
#     name: judge-network
#   traefik-public:
#     name: traefik-public
#     external: true
