services:
  db:
    image: mariadb:11.2
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${DJ_DB}
      MYSQL_USER: ${DJ_DB_USER}
      MYSQL_PASSWORD: ${DJ_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      CONTAINER_TIMEZONE: Asia/Kolkata
    command: 
      --max-connections=1000 
      --max-allowed-packet=512M
      --performance-schema=ON
      --join-buffer-size=4M
      --innodb-buffer-pool-size=15G
      --innodb-log-file-size=32M
      --innodb-log-buffer-size=32M
      --query-cache-size=0
      --query-cache-type=0
      --tmp-table-size=512M
      --max-heap-table-size=512M      
      --slow-query-log=1
      --slow-query-log-file=/var/lib/mysql/mariadb-slow.log
      --long-query-time=1
    volumes:
      - db-data:/var/lib/mysql
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    restart: always
    networks:
      - mariadb-network

volumes:
  db-data:
    name: mariadb-db-data

networks:
  mariadb-network:
    name: mariadb-network